filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /app/logs/*.log
    fields:
      service_name: authorization-app
    json.keys_under_root: true
    json.overwrite_keys: true
    json.message_key: "message"

output.logstash:
  hosts: ["logstash:5000"]