#version: '7.17.3'

services:

  authorization-app:
    build: .
    container_name: authorization-service
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./logs:/app/logs
    networks:
      - elk-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.3
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - 5000:5000/tcp
      - 9600:9600
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.3
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elk-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.3
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/app/logs:ro
    command: ["-e", "-c", "/usr/share/filebeat/filebeat.yml"]
    depends_on:
      - authorization-app
      - logstash
    networks:
      - elk-network

volumes:
  elasticsearch-data:
    driver: local

networks:
  elk-network:
    driver: bridge