version: '3.8'

services:
  authorization-app:
    build: .
    container_name: authorization-service
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./logs:/app/logs
    networks:
      - elk-network
      - monitoring-network
    environment:

      JAVA_TOOL_OPTIONS: "-Xmx1024m -Xms256m"

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus_data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle
    networks:
      - monitoring-network
    depends_on:
      - authorization-app

  grafana:
    image: grafana/grafana:10.1.5
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring-network
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    command: --config.file=/etc/alertmanager/config.yml
    networks:
      - monitoring-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.3
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - 5000:5000/tcp
      - 9600:9600
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.3
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elk-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.3
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/app/logs:ro
    command: ["-e", "-c", "/usr/share/filebeat/filebeat.yml"]
    depends_on:
      - authorization-app
      - logstash
    networks:
      - elk-network

volumes:
  elasticsearch-data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  elk-network:
    driver: bridge
  monitoring-network:
    driver: bridge